"""
Auto-generated by training/train_denomination_classifier.py.
Class index -> denomination label mapping, matching the exact
training-time class order. Do not hand-edit the ordering -- rerun
training (or edit both this file and the ONNX model consistently)
if it needs to change.
"""

DENOMINATION_LABELS = {
    0: '10',
    1: '100',
    2: '20',
    3: '200',
    4: '2000',
    5: '50',
    6: '500',
}
